name: CI

on: push

jobs:
	install_py:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- name: Setup Python
				- uses: actions/setup-python@v2
				with:
					python-version: '3.10'
			- run: |
				python -m pip install --upgrade pip
				pip install sqlite3
				pip install aiogram

	deploy:
		runs-on: ubuntu-latest
		needs: install_py
		- run: python main.py

		#- name: run_bat
		#  shell: bash
		#  run: ./tgbot/bot_run.bat
		
